"""Fix Device Token Table

Revision ID: b8731bafd590
Revises: 31e898cfdb86
Create Date: 2026-07-02 08:52:17.733308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8731bafd590'
down_revision: Union[str, Sequence[str], None] = '31e898cfdb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('admin_id', sa.String(length=36), nullable=False))
    op.drop_constraint(op.f('device_tokens_profile_id_fkey'), 'device_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'device_tokens', 'admins', ['admin_id'], ['id'])
    op.drop_column('device_tokens', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_tokens', sa.Column('profile_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'device_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('device_tokens_profile_id_fkey'), 'device_tokens', 'profiles', ['profile_id'], ['id'])
    op.drop_column('device_tokens', 'admin_id')
    # ### end Alembic commands ###
